import "./globals.css";
import { Analytics } from "@vercel/analytics/next";
export const metadata = {
  title: "MathRix'25",
  description: "Generated by create next app",
  image: "/images/logo.png",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/png" href="/images/logo.png" />
        <link rel="icon" type="image/x-icon" href="/images/logo.png" />
      </head>
      <body className="no-scrollbar">
        {/* <Header/> */}
        {children}
        <Analytics />
      </body>
      {/* <Footer/> */}
    </html>
  );
}
